language: python
python:
  - "3.6"

sudo: enabled

git:
  submodules: false

before_install:
  - pip install -r requirements-travis.txt
  - sudo apt -qq update
  - sudo apt install -y automake git python3-pip gettext pkgconf xsltproc python3-dev systemd logrotate openssl nginx gettext
  - ./autogen.sh --system

install: make

before_script: cd tests

script:
  - make check-local
  - make check
