#!/bin/bash
#
# Project Wok
#
# Copyright IBM Corp, 2016
#
# Code derived from Project Kimchi
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software

for src in `cat POTFILES.in`; do
    if [ ${src: -3} == ".py" ]; then
        cat $src
    else
        cat $src | cheetah compile -
    fi
done | xgettext --no-location -o sample.pot -L Python -

for lingua in `cat LINGUAS`; do
    msgmerge --update --no-fuzzy-matching --backup=off $lingua.po sample.pot 
    msgfmt -c --statistics --verbose -o $lingua.gmo $lingua.po
done

