name: wok-CI
on: ["push", "pull_request"]

jobs:
  build-and-test-wok:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        container: ["ubuntu:bionic", "fedora:31", "opensuse/leap:42.3", "centos8"]

    container:
      image: ${{ matrix.container }}
    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: setup deps and make
        run: |
          bash .github/scripts/setup_wok_ubuntu.sh
        shell: bash

      - name: run tests
        working-directory: ./tests
        run: |
          sudo make check-local
          sudo make check
        shell: bash
